ENTRIES_BATCH2 = [
    {
        "word": "grit",
        "cn": "砂石;粗砂",
        "en": "grit (coarse sand and gravel)",
        "root": "英语借词 grit,无印尼语词根形态",
        "forms_note": "-(无派生形态)",
        "note": "英语借词(grit),水处理专业术语,指粗砂砾",
        "synonyms": ["pasir kasar", "kerikil halus"],
        "antonyms": [],
        "examples": [
            ("水处理", "Partikel grit yang mengendap di bak penangkap harus disedot secara berkala.", "沉砂池中沉积的砂石颗粒必须定期抽吸清除。"),
            ("水处理", "Grit kasar dan kerikil dipisahkan pada tahap pra-pengolahan air limbah.", "粗砂和砾石在废水预处理阶段被分离。"),
        ],
    },
    {
        "word": "pasir",
        "cn": "沙子",
        "en": "sand",
        "root": "词根 pasir(名词)",
        "forms_note": "berpasir(多沙的);pasiran(砂质的)",
        "note": "",
        "synonyms": ["grit"],
        "antonyms": [],
        "examples": [
            ("工程建设", "Pondasi tangki penampungan dibangun di atas lapisan pasir padat.", "储罐基础建在密实的砂层上。"),
            ("水处理", "Filter pasir silika digunakan pada tahap akhir pengolahan air bersih.", "石英砂过滤器用于净水处理的最终阶段。"),
        ],
    },
    {
        "word": "sedimentasi",
        "cn": "沉淀",
        "en": "sedimentation",
        "root": "sedimen(沉淀物,名词)+ -asi(名词后缀)",
        "forms_note": "sedimen(沉淀物);mengendap(沉淀,动词);pengendapan(沉淀过程,名词)",
        "note": "英语/拉丁借词(sedimentation)",
        "synonyms": ["pengendapan"],
        "antonyms": [],
        "examples": [
            ("水处理", "Proses sedimentasi primer menghilangkan lumpur dan partikel tersuspensi dari air limbah.", "初沉过程去除废水中的污泥和悬浮颗粒。"),
            ("环保合规", "Laju sedimentasi logam berat di kolom pengendap sesuai dengan hasil kajian lingkungan.", "沉降柱中重金属的沉降速率与环境评估结果一致。"),
        ],
    },
    {
        "word": "lumpur",
        "cn": "泥浆;污泥",
        "en": "mud; sludge",
        "root": "词根 lumpur(名词)",
        "forms_note": "berlumpur(泥泞的);melumpurkan(使成泥)",
        "note": "在废水处理语境中常译作「污泥」",
        "synonyms": [],
        "antonyms": [],
        "examples": [
            ("水处理", "Lumpur aktivasi dari unit pengolahan air limbah diolah di unit pengering lumpur.", "废水处理单元的活性污泥在污泥干化单元处理。"),
            ("应急处置", "Tumpahan lumpur tailing harus segera dilaporkan kepada Dinas Lingkungan Hidup.", "尾矿泥浆溢流必须立即向环境局报告。"),
        ],
    },
    {
        "word": "filtrasi",
        "cn": "过滤",
        "en": "filtration",
        "root": "filter(过滤器,英语借词)+ -asi(名词后缀)",
        "forms_note": "filter(过滤器);memfilter(过滤,动词);penyaringan(过滤,名词)",
        "note": "英语借词(filtration)",
        "synonyms": ["penyaringan"],
        "antonyms": [],
        "examples": [
            ("水处理", "Sistem filtrasi bertingkat menghasilkan efluen yang memenuhi standar internasional.", "多级过滤系统产出符合国际标准的出水。"),
            ("环保合规", "Media filtrasi wajib diganti setiap tiga bulan untuk menjaga kualitas air buangan.", "过滤介质必须每三个月更换,以保证外排水质。"),
        ],
    },
    {
        "word": "disinfeksi",
        "cn": "消毒",
        "en": "disinfection",
        "root": "dis-(分离/去除前缀)+ infeksi(感染,英语借词)",
        "forms_note": "disinfektan(消毒剂);mendisinfeksi(消毒,动词)",
        "note": "英语借词(disinfection)",
        "synonyms": [],
        "antonyms": [],
        "examples": [
            ("水处理", "Tahap disinfeksi dengan klorin membunuh bakteri patogen dalam air minum.", "用氯消毒的阶段杀灭饮用水中的致病菌。"),
            ("安全卫生", "Area mess karyawan didisinfeksi secara berkala untuk mencegah penyebaran penyakit.", "员工宿舍区定期消毒,防止疾病传播。"),
        ],
    },
    {
        "word": "scrubber",
        "cn": "洗涤器(烟气处理)",
        "en": "scrubber (gas cleaning unit)",
        "root": "英语借词 scrubber,无印尼语词根形态",
        "forms_note": "-(无派生形态)",
        "note": "英语借词(scrubber),烟气脱硫/除尘设备",
        "synonyms": [],
        "antonyms": [],
        "examples": [
            ("烟气处理", "Scrubber di cerobong smelter menurunkan kadar partikulat di bawah batas emisi.", "冶炼厂烟囱的洗涤器将颗粒物浓度降至排放限值以下。"),
            ("应急处置", "Alarm kegagalan scrubber berbunyi, tim HSE segera turun ke lapangan.", "洗涤器故障警报响起,HSE 团队立即赶赴现场。"),
        ],
    },
    {
        "word": "partikulat",
        "cn": "颗粒物",
        "en": "particulate (matter)",
        "root": "partikel(颗粒,英语借词)+ -at(名词/形容词后缀)",
        "forms_note": "partikel(颗粒,名词)",
        "note": "英语借词(particulate),环境监测指标 PM2.5/PM10 的学术名称",
        "synonyms": ["partikel"],
        "antonyms": [],
        "examples": [
            ("环保合规", "Monitoring partikulat PM2.5 dan PM10 dilakukan harian di sekitar kawasan pabrik.", "厂区周边每日监测 PM2.5 和 PM10 颗粒物。"),
            ("环保合规", "Emisi partikulat dari tungku peleburan dilaporkan dalam laporan bulanan lingkungan.", "熔炼炉颗粒物排放在环境月度报告中申报。"),
        ],
    },
    {
        "word": "debu",
        "cn": "灰尘;粉尘",
        "en": "dust",
        "root": "词根 debu(名词)",
        "forms_note": "berdebu(布满灰尘的)",
        "note": "",
        "synonyms": [],
        "antonyms": [],
        "examples": [
            ("安全健康", "Pekerja wajib memakai respirator di area dengan kadar debu tinggi.", "工人在高粉尘区域必须佩戴呼吸器。"),
            ("环保合规", "Penyiraman jalan berkala mengurangi debu yang beterbangan ke permukiman warga.", "定期道路喷淋减少飘向居民区的扬尘。"),
        ],
    },
    {
        "word": "tingkatan",
        "cn": "等级;层次",
        "en": "level; tier; grade",
        "root": "tingkat(层级,名词)+ -an(名词后缀)",
        "forms_note": "tingkat(层级);meningkat(上升);meningkatkan(提升);peningkatan(提升,名词)",
        "note": "",
        "synonyms": ["jenjang", "level"],
        "antonyms": [],
        "examples": [
            ("项目管理", "Proyek dibagi menjadi tiga tingkatan prioritas sesuai urgensi implementasi.", "项目按实施紧迫性分为三个优先等级。"),
            ("水处理", "Tingkatan filtrasi ditentukan berdasarkan kualitas air baku.", "过滤级数根据原水水质确定。"),
        ],
    },
    {
        "word": "mengurangi",
        "cn": "减少;降低",
        "en": "to reduce; to decrease",
        "root": "meng-(动词前缀)+ kurang(少,形容词)+ -i(及物化后缀)",
        "forms_note": "kurang(缺少);berkurang(减少,自动);pengurangan(削减,名词)",
        "note": "",
        "synonyms": ["menekan", "memangkas"],
        "antonyms": ["menambah", "meningkatkan"],
        "examples": [
            ("环保合规", "Perusahaan berkomitmen mengurangi emisi gas buang sebesar dua puluh persen dalam lima tahun.", "公司承诺五年内减少废气排放百分之二十。"),
            ("项目管理", "Otomasi proses produksi terbukti mengurangi angka kecelakaan kerja.", "生产自动化被证明能降低工伤事故率。"),
        ],
    },
    {
        "word": "teriak",
        "cn": "喊叫;大声呼喊",
        "en": "to shout; to yell",
        "root": "词根 teriak(拟声根)",
        "forms_note": "berteriak(大喊);teriakan(喊声,名词)",
        "note": "语气较强,正式场合多用 berseru",
        "synonyms": ["berseru"],
        "antonyms": [],
        "examples": [
            ("应急处置", "Korban yang terjebak di ruang tertutup berteriak meminta tolong.", "被困密闭空间的受害者大声呼救。"),
            ("现场管理", "Pengawas melarang berteriak di area produksi untuk mencegah kepanikan.", "安全员禁止在生产区喊叫,以防恐慌。"),
        ],
    },
    {
        "word": "pilihan",
        "cn": "选择;选项",
        "en": "choice; option",
        "root": "pilih(选择,动词)+ -an(名词后缀)",
        "forms_note": "pilih(选择);memilih(挑选);pemilihan(选举/选择过程);terpilih(当选/被选中)",
        "note": "",
        "synonyms": ["alternatif", "opsi"],
        "antonyms": [],
        "examples": [
            ("商务谈判", "Kami menawarkan tiga pilihan skema pembayaran kepada mitra dagang.", "我们向贸易伙伴提供三种付款方案。"),
            ("项目管理", "Pilihan lokasi pembangunan IPAL ditetapkan setelah kajian lingkungan.", "污水处理厂选址在环境评估后确定。"),
        ],
    },
    {
        "word": "mengandung",
        "cn": "含有;包含",
        "en": "to contain",
        "root": "meng-(动词前缀,遇 k 时 k 脱落)+ kandung(包容,词根)",
        "forms_note": "kandung(词根);kandungan(含量/内容,名词);terkandung(被包含)",
        "note": "meng- 前缀遇词根首字母 k 时,k 脱落",
        "synonyms": ["berisi", "memuat"],
        "antonyms": [],
        "examples": [
            ("环保合规", "Air limbah yang mengandung logam berat dilarang dibuang langsung ke sungai.", "含重金属的废水禁止直接排入河流。"),
            ("烟气处理", "Gas buang yang mengandung belerang harus melewati scrubber sebelum ke cerobong.", "含硫废气必须在进烟囱前经过洗涤器。"),
        ],
    },
    {
        "word": "logam",
        "cn": "金属",
        "en": "metal",
        "root": "词根 logam(名词)",
        "forms_note": "berlogam(含金属的)",
        "note": "",
        "synonyms": [],
        "antonyms": ["nonlogam"],
        "examples": [
            ("冶炼技术", "Smelter mengolah bijih nikel menjadi logam dengan kadar kemurnian tinggi.", "冶炼厂将镍矿石加工成高纯度金属。"),
            ("环保合规", "Uji laboratorium memastikan sedimen sungai tercemar logam berat.", "实验室检测确认河流沉积物受重金属污染。"),
        ],
    },
    {
        "word": "kebocoran",
        "cn": "泄漏",
        "en": "leakage; leak",
        "root": "ke-(名词前缀)+ bocor(漏,形容词/动词)+ -an(名词后缀)",
        "forms_note": "bocor(漏);membocorkan(使泄漏,及物动词);terbocorkan(被泄露)",
        "note": "",
        "synonyms": ["rembesan"],
        "antonyms": [],
        "examples": [
            ("应急处置", "Kebocoran tangki asam memicu prosedur darurat dan evakuasi area.", "酸罐泄漏触发应急程序和区域疏散。"),
            ("设备维护", "Inspeksi rutin mencegah kebocoran pipa di unit pengolahan air limbah.", "定期巡检防止废水处理单元管道泄漏。"),
        ],
    },
    {
        "word": "betina",
        "cn": "雌性的",
        "en": "female (of animals)",
        "root": "词根 betina(名词/形容词)",
        "forms_note": "kebetinaan(雌性气质/女性特质,名词)",
        "note": "多用于动物,指人时用 perempuan/wanita",
        "synonyms": [],
        "antonyms": ["jantan"],
        "examples": [
            ("环境监测", "Peneliti menandai katak betina sebagai indikator kualitas ekosistem sungai.", "研究人员标记雌蛙作为河流生态质量指示物种。"),
            ("生物科技", "Pemilihan induk betina sehat menjadi kunci program pemuliaan ikan.", "选择健康雌性亲本是鱼类育种计划的关键。"),
        ],
    },
    {
        "word": "jantan",
        "cn": "雄性的",
        "en": "male (of animals)",
        "root": "词根 jantan(形容词/名词)",
        "forms_note": "kejantanan(雄性气质,名词)",
        "note": "多用于动物,指人时用 laki-laki/pria",
        "synonyms": [],
        "antonyms": ["betina"],
        "examples": [
            ("生物科技", "Ikan lele jantan tumbuh lebih cepat dibandingkan yang betina.", "雄性胡子鲶比雌性生长更快。"),
            ("环境监测", "Populasi burung jantan berkurang akibat hilangnya habitat di kawasan industri.", "工业区栖息地丧失导致雄鸟种群减少。"),
        ],
    },
    {
        "word": "ingjak",
        "cn": "踩;踏",
        "en": "to step on; to tread",
        "root": "疑为 injak 的非标准拼写变体;标准词根 injak(动词)",
        "forms_note": "injak(标准形式);menginjak(踩踏);terinjak(被踩);injakan(落脚处,名词)",
        "note": "非标准拼写,标准印尼语应为 injak;例句使用标准形式",
        "synonyms": ["memijak", "menginjak"],
        "antonyms": [],
        "examples": [
            ("安全标识", "Dilarang menginjak pipa proses di atas parit untuk mencegah kecelakaan.", "禁止踩踏管沟上方的工艺管道以防事故。"),
            ("现场管理", "Area tumpahan bahan kimia tidak boleh diinjak sebelum dibersihkan.", "化学品溢流区域清理前不得踩踏。"),
        ],
    },
    {
        "word": "berkomitmen",
        "cn": "承诺;致力于",
        "en": "to commit (to)",
        "root": "ber-(动词前缀)+ komitmen(承诺,英语 commitment 借词)",
        "forms_note": "komitmen(承诺,名词)",
        "note": "由英语借词 commitment 派生",
        "synonyms": ["berjanji", "berikrar"],
        "antonyms": ["mengingkari"],
        "examples": [
            ("商务合作", "Perusahaan berkomitmen mematuhi standar lingkungan internasional dalam setiap proyek.", "公司承诺每个项目均遵守国际环境标准。"),
            ("项目管理", "Tim proyek berkomitmen menyelesaikan pembangunan IPAL sebelum musim hujan.", "项目团队承诺在雨季前完成污水处理厂建设。"),
        ],
    },
    {
        "word": "berjanji",
        "cn": "许诺;答应",
        "en": "to promise",
        "root": "ber-(动词前缀)+ janji(诺言,名词)",
        "forms_note": "janji(诺言);menjanjikan(许诺/有前途,及物动词);janjian(约定,名词)",
        "note": "",
        "synonyms": ["berkomitmen", "berikrar"],
        "antonyms": ["mengingkari"],
        "examples": [
            ("商务谈判", "Kontraktor berjanji menuntaskan perbaikan scrubber sebelum akhir kuartal.", "承包商承诺在季度末前完成洗涤器修复。"),
            ("团队协作", "Saya berjanji melaporkan hasil uji kualitas air setiap Senin pagi.", "我承诺每周一早晨报告水质检测结果。"),
        ],
    },
]
