# -*- coding: utf-8 -*-
# BIT V1.0 词条批次：entries_1005_b1（12词）
# 生成时间：2026-10-06 22:39 CST
# 语境：供应链管理 / 商务谈判 / 冶炼工业园区

ENTRIES = [
    {
        "word": "rantai",
        "cn": "链条",
        "en": "chain",
        "root": "词根 rantai（名词词基，单一词素；疑源自古爪哇语 rantay）",
        "forms_note": "复合/派生：rantai pasok（供应链）、rantai dingin（冷链）、rantai nilai（价值链）；名词无词形变化",
        "note": "高频搭配 rantai pasok = 供应链",
        "synonyms": [],
        "antonyms": [],
        "examples": [
            ("供应链", "Rantai pasok nikel dari tambang ke smelter harus terus dijaga.", "从矿山到冶炼厂的镍供应链必须持续保障。"),
            ("物流", "Satu gangguan transportasi bisa memutus seluruh rantai logistik.", "一次运输中断就可能切断整个物流链。"),
        ],
    },
    {
        "word": "pasok",
        "cn": "供应",
        "en": "supply; to supply",
        "root": "词根 pasok（动词/名词词基，单一词素）",
        "forms_note": "派生：memasok（v. 供应）、pasokan（n. 供应/补给）、pemasok（n. 供应商）",
        "note": "",
        "synonyms": ["suplai"],
        "antonyms": [],
        "examples": [
            ("供应链", "Pasok bijih nikel ke kawasan industri mulai menurun bulan ini.", "本月对工业园区的镍矿石供应开始下降。"),
            ("采购", "Kami memastikan pasok bahan bakar tetap lancar selama proyek berjalan.", "我们确保项目期间燃料供应保持畅通。"),
        ],
    },
    {
        "word": "menawar",
        "cn": "讨价还价/砍价",
        "en": "to bargain; to haggle; to bid",
        "root": "meN-（动词前缀）+ tawar（词根：出价；淡）→ menawar；meN- 使词根首字母 t- 脱落",
        "forms_note": "变形：tawar（词根）、tawar-menawar（讨价还价，名词化）、penawar（n. 出价人；解药）、penawaran（n. 报价/要约）、menawari（v. 向…报价）",
        "note": "",
        "synonyms": ["menyawar"],
        "antonyms": [],
        "examples": [
            ("商务谈判", "Kami menawar harga pembelian hingga 10% di bawah penawaran awal.", "我们把采购价谈到了低于初始报价10%。"),
            ("采购", "Dia terampil menawar setiap invoice sebelum disetujui.", "他擅长在每张发票获批前砍价。"),
        ],
    },
    {
        "word": "melayani",
        "cn": "服务（动词）",
        "en": "to serve",
        "root": "me-（及物化前缀）+ layan（词根：服侍）+ -i（后缀）→ melayani",
        "forms_note": "变形：layan（词根）、layanan（n. 服务）、pelayan（n. 服务员）、pelayanan（n. 服务/效劳）、melayaninya（附着代词形式）",
        "note": "",
        "synonyms": [],
        "antonyms": [],
        "examples": [
            ("客户服务", "Helpdesk kami melayani permintaan klien 24 jam sehari.", "我们的服务台每天24小时响应客户需求。"),
            ("园区服务", "Kantor kawasan melayani izin masuk tamu secara online.", "园区办公室在线办理访客入园许可。"),
        ],
    },
    {
        "word": "penalti",
        "cn": "违约金/罚款",
        "en": "penalty; fine",
        "root": "借词（荷兰语 penalty / 英语 penalty），根 penalti 为单一词素",
        "forms_note": "—（无派生形态）",
        "note": "体育语境 = 点球；商务/合同语境 = 违约金、罚款",
        "synonyms": ["denda"],
        "antonyms": [],
        "examples": [
            ("合同", "Penalti keterlambatan dihitung 0,5% per hari sesuai kontrak.", "延误违约金按合同每天0.5%计算。"),
            ("体育", "Penalti di babak kedua mengubah skor menjadi 2-1.", "下半场的点球把比分改写为2比1。"),
        ],
    },
    {
        "word": "pasif",
        "cn": "被动的",
        "en": "passive",
        "root": "借词（荷兰语 passief），根 pasif 为单一词素",
        "forms_note": "—（无常用派生形态）",
        "note": "",
        "synonyms": [],
        "antonyms": ["aktif"],
        "examples": [
            ("商务谈判", "Sikap pasif dalam negosiasi membuat kita kehilangan momentum.", "谈判中的被动姿态会让我们失去主动权。"),
            ("审计", "Auditor pasif hanya mencatat temuan tanpa memberi rekomendasi.", "被动式审计只记录问题而不给出建议。"),
        ],
    },
    {
        "word": "aktif",
        "cn": "活跃的/主动的",
        "en": "active",
        "root": "借词（荷兰语 aktief），根 aktif 为单一词素",
        "forms_note": "派生：aktivitas（n. 活动）、aktivis（n. 积极分子）、mengaktifkan（v. 激活/使活跃）、keaktifan（n. 活跃性）",
        "note": "",
        "synonyms": ["giat"],
        "antonyms": ["pasif"],
        "examples": [
            ("投资", "Perusahaan asing tetap aktif berinvestasi di kawasan Morowali.", "外国企业在莫罗瓦利园区持续活跃地投资。"),
            ("谈判", "Tim kami aktif mengusulkan revisi klausul penalti.", "我们团队主动提议修改违约金条款。"),
        ],
    },
    {
        "word": "klausa-dalam-tata-bahasa",
        "cn": "语法从句",
        "en": "clause (in grammar)",
        "root": "复合构词：klausa（借自拉丁语 clausa，经荷兰语）+ dalam（固有介词：在…中）+ tata（固有名词：体系/编排）+ bahasa（借自梵语 bhāṣā：语言）",
        "forms_note": "整体收录（长连字符词）：klausa + dalam + tata + bahasa；相关：klausa bebas（自由从句）、klausa terikat（粘附从句）",
        "note": "构成：klausa+dalam+tata+bahasa；整体作名词用，BIT 体例按长连字符词整体收录",
        "synonyms": ["anak kalimat"],
        "antonyms": [],
        "examples": [
            ("语法学习", "Klausa dalam tata bahasa Indonesia dibedakan menjadi klausa bebas dan klausa terikat.", "印尼语语法中的从句区分为自由从句和粘附从句。"),
            ("语言考试", "Soal uji menanyakan fungsi klausa dalam tata bahasa kalimat majemuk.", "考题询问复合句中语法从句的功能。"),
        ],
    },
    {
        "word": "menelpon",
        "cn": "打电话",
        "en": "to phone; to call",
        "root": "meN-（动词前缀）+ telepon（借词：telephone）→ 标准 menelepon；meN- 使词根首字母 t- 脱落；menelpon 为 -e- 脱落的口语变体",
        "forms_note": "标准形式：menelepon（正式/书面）；变体：menelefon、menelpon（口语/非正式）；派生：telepon（n. 电话）",
        "note": "= menelepon 的口语变体，正式文本用 menelepon",
        "synonyms": ["menelepon", "menelefon"],
        "antonyms": [],
        "examples": [
            ("采购沟通", "Saya menelpon pemasok untuk mengonfirmasi jadwal kirim.", "我给供应商打电话确认发货时间。"),
            ("应急", "Dalam keadaan darurat, menelpon lebih cepat daripada mengirim pesan.", "紧急情况下，打电话比发消息快。"),
        ],
    },
    {
        "word": "jadi",
        "cn": "所以/成为",
        "en": "so; to become",
        "root": "词根 jadi（印尼语固有词，单一词素；可作连词/动词/形容词）",
        "forms_note": "变形：menjadi（v. 成为）、menjadikan（v. 使成为）、kejadian（n. 事件）、sejadi-jadinya（竭尽全力，固定习语）",
        "note": "兼类词：连词（所以）/ 动词（成为）/ 形容词（成品，如 produk jadi）",
        "synonyms": ["maka"],
        "antonyms": [],
        "examples": [
            ("总结", "Jadi, kita sepakat dengan harga lima juta per ton.", "所以，我们同意每吨五百万的价格。"),
            ("工业", "Bijih mentah diolah menjadi produk setengah jadi.", "原矿被加工成半成品。"),
        ],
    },
    {
        "word": "mentah",
        "cn": "生的/原材料",
        "en": "raw; uncooked",
        "root": "词根 mentah（形容词词基，单一词素）",
        "forms_note": "派生：mentahan（n. 生料/原材料）；反义对比：matang（熟的/成品的）",
        "note": "bahan mentah = 原材料（冶炼/制造业高频搭配）",
        "synonyms": [],
        "antonyms": ["matang"],
        "examples": [
            ("冶炼", "Smelter mengolah bijih nikel mentah menjadi feronikel.", "冶炼厂把原镍矿石加工成镍铁。"),
            ("数据", "Data mentah produksi harus diverifikasi sebelum pelaporan.", "生产原始数据在报出前必须核实。"),
        ],
    },
    {
        "word": "ditrima",
        "cn": "被接收",
        "en": "received (nonstandard for diterima)",
        "root": "di-（被动前缀）+ trima ← terima（词根：接收）的误拼；标准构成：di- + terima → diterima",
        "forms_note": "标准变形：terima（词根）、menerima（v. 接收）、diterima（被动标准形）、penerimaan（n. 接收/验收）、penerima（n. 接收人）",
        "note": "非标准拼写（常见于短信/社媒等非正式书写）；标准形式 diterima = di-（被动前缀）+ terima（接收）",
        "synonyms": ["diterima"],
        "antonyms": ["ditolak"],
        "examples": [
            ("收货", "Barang ditrima gudang tadi malam tanpa surat jalan.", "货物昨晚在没有送货单的情况下被仓库接收了。"),
            ("日常沟通", "Email saya ditrima, tetapi belum ada balasan.", "我的邮件被收到了，但还没有回复。"),
        ],
    },
]
