# -*- coding: utf-8 -*-
# BIT V1.0 词条批次 3（33词）——脱碳减排/项目管理语境
# 格式：word/cn/en/root/forms_note/note/synonyms/antonyms/examples

ENTRIES_BATCH3 = [
    {
        "word": "mencapai",
        "cn": "达到；实现",
        "en": "to reach; to achieve",
        "root": "capai（达到——本土词）+ me-（主动前缀）→ mencapai",
        "forms_note": "mencapai 动词；dicapai 被动动词；capaian 名词（成果；达成量）；tercapai 被动完成（已实现）",
        "note": "",
        "synonyms": ["meraih（赢得）", "merealisasikan（实现——借词）"],
        "antonyms": ["gagal mencapai（未能达到）", "melewatkan（错过）"],
        "examples": [
            ("项目管理", "Tim berhasil mencapai target produksi bulanan tepat waktu.", "团队成功按期达成月度生产目标。"),
            ("商务", "Perusahaan mencapai kesepakatan dengan mitra Jepang tentang pasokan nikel.", "公司与日本伙伴就镍供应达成协议。"),
        ],
    },
    {
        "word": "dekarbonisasi",
        "cn": "脱碳",
        "en": "decarbonization",
        "root": "dekarbonisasi（欧洲语言借词：英 decarbonization / 荷 dekarbonisatie；构词 de-（去除）+ karbon（碳——拉丁借词）+ -isasi（化））",
        "forms_note": "dekarbonisasi 名词；mendekarbonisasi 动词（使脱碳）；terdekarbonisasi 被动（已脱碳）",
        "note": "气候政策核心词：印尼 Net Zero Emission 2060 路径的关键行动；冶炼园区绿电转型属工业脱碳（dekarbonisasi industri）。",
        "synonyms": ["netralisasi karbon（碳中和——目标义近）"],
        "antonyms": [],
        "examples": [
            ("脱碳减排", "Dekarbonisasi industri nikel memerlukan listrik hijau dalam skala besar.", "镍产业脱碳需要大规模绿电。"),
            ("项目管理", "Roadmap dekarbonisasi pabrik disusun dalam tiga fase pelaksanaan.", "工厂脱碳路线图按三个阶段编制。"),
        ],
    },
    {
        "word": "langkah-pertama",
        "cn": "第一步",
        "en": "the first step",
        "root": "langkah（步；步骤——本土词）+ pertama（第一——本土词），合成名词",
        "forms_note": "langkah pertama 名词短语（规范书写分写）；langkah-langkah 复数（各步骤）",
        "note": "规范书写为分写 langkah pertama；连字符形式按保守不拆原则作整体词条收录。",
        "synonyms": ["tahap awal（初始阶段）", "awalan（开端）"],
        "antonyms": ["langkah terakhir（最后一步）"],
        "examples": [
            ("项目管理", "Audit energi adalah langkah pertama sebelum investasi efisiensi.", "能效投资前，能源审计是第一步。"),
            ("商务", "Membangun kepercayaan merupakan langkah pertama dalam negosiasi jangka panjang.", "建立信任是长期谈判的第一步。"),
        ],
    },
    {
        "word": "mengukur",
        "cn": "测量",
        "en": "to measure",
        "root": "ukur（量——本土词）+ me- → mengukur",
        "forms_note": "mengukur 动词；diukur 被动动词；pengukuran 名词（测量）；pengukur 名词（测量仪表）；ukuran 名词（尺寸；尺度）",
        "note": "",
        "synonyms": ["menimbang（称量——限于重量）"],
        "antonyms": ["memperkirakan（估算——非实测）"],
        "examples": [
            ("项目管理", "Teknisi mengukur emisi gas buang sesuai metode standar ISO.", "技术员按 ISO 标准方法测量废气排放。"),
            ("脱碳减排", "Kami mengukur jejak karbon rantai pasok mulai dari bahan baku.", "我们从原料端测量供应链碳足迹。"),
        ],
    },
    {
        "word": "metodologi",
        "cn": "方法论",
        "en": "methodology",
        "root": "metodologi（欧洲语言借词：英 methodology / 荷 methodologie，终源希腊语 methodos「方法」+ logos「学问」）",
        "forms_note": "metodologi 名词；metodologis 形容词（方法论的）；metodolog 名词（方法论学者）",
        "note": "碳核算高频：inventarisasi GRK mengikuti metodologi IPCC（温室气体清单遵循 IPCC 方法论）。",
        "synonyms": ["kaedah（方法体系——正式语）", "pendekatan（路径方法）"],
        "antonyms": [],
        "examples": [
            ("脱碳减排", "Inventarisasi GRK mengikuti metodologi IPCC tingkat Tier 2.", "温室气体清单编制遵循 IPCC Tier 2 方法论。"),
            ("项目管理", "Metodologi manajemen proyek PRINCE2 diadopsi untuk proyek pembangkit.", "电厂项目采用 PRINCE2 项目管理方法论。"),
        ],
    },
    {
        "word": "protokol",
        "cn": "议定书；协议；规程",
        "en": "protocol",
        "root": "protokol（欧洲语言借词：英 protocol / 荷 protocol，终源希腊语 protokollon「扉页」）",
        "forms_note": "protokol 名词；protokoler 形容词（礼仪的）；protokol keselamatan 名词短语（安全规程）",
        "note": "双义：①国际条约义——Protokol Kyoto《京都议定书》（气候变化框架）；②操作规程义——protokol keselamatan kerja（安全作业规程）。",
        "synonyms": ["prosedur（程序）", "tata tertib（规程——本土构词）"],
        "antonyms": [],
        "examples": [
            ("气候变化", "Indonesia meratifikasi Protokol Kyoto untuk menanggapi perubahan iklim.", "印尼批准《京都议定书》以应对气候变化。"),
            ("项目管理", "Semua pekerja wajib mengikuti protokol keselamatan sebelum memasuki area smelter.", "所有人员进入冶炼区前必须遵守安全规程。"),
        ],
    },
    {
        "word": "GRK",
        "cn": "温室气体",
        "en": "greenhouse gas (GHG)",
        "root": "GRK（首字母缩写词，全称 Gas Rumah Kaca）",
        "forms_note": "GRK 缩写名词（大写保留）；gas rumah kaca 全称分写形式；emisi GRK 名词短语（温室气体排放）",
        "note": "全称 Gas Rumah Kaca（温室气体）；缩写大写保留。气候变化谈判与碳核算核心术语，主要种类：CO₂、CH₄、N₂O、F-gas。",
        "synonyms": ["gas rumah kaca（全称）"],
        "antonyms": [],
        "examples": [
            ("脱碳减排", "Laporan inventarisasi GRK diserahkan ke kementerian setiap tahun.", "温室气体清单报告每年提交部委。"),
            ("商务", "Penurunan intensitas GRK menjadi komitmen utama dalam laporan keberlanjutan.", "温室气体强度下降成为可持续报告的核心承诺。"),
        ],
    },
    {
        "word": "rantai-pasok",
        "cn": "供应链",
        "en": "supply chain",
        "root": "rantai（链——本土词）+ pasok（供应——本土词），合成名词",
        "forms_note": "rantai pasok 名词短语（规范书写分写）；pemasok 名词（供应商）；pasokan 名词（供应）；rantai nilai 关联词（价值链）",
        "note": "规范书写为分写 rantai pasok；连字符形式按保守不拆原则作整体词条收录。碳核算高频：emisi rantai pasok（供应链排放——范围3主要来源）。",
        "synonyms": ["rantai nilai（价值链——义域有别）", "mata rantai pasokan（供应环节）"],
        "antonyms": [],
        "examples": [
            ("供应链", "Gangguan rantai pasok memperlambat kedatangan suku cadang pabrik.", "供应链中断延迟了工厂备件到货。"),
            ("脱碳减排", "Perusahaan menelusuri jejak karbon rantai pasok hingga pemasok tingkat tiga.", "公司追溯供应链碳足迹直至三级供应商。"),
        ],
    },
    {
        "word": "lingkup-3",
        "cn": "范围3（碳排放核算）",
        "en": "Scope 3 (emissions accounting)",
        "root": "lingkup（范围——本土词）+ 3（数字，译自英 Scope 3）",
        "forms_note": "lingkup 1 名词短语（范围1——直接排放）；lingkup 2 名词短语（范围2——外购能源间接排放）；lingkup 3 名词短语（范围3——价值链其他间接排放）",
        "note": "温室气体核算体系（GHG Protocol）三分法：范围1=直接排放，范围2=外购电力热力间接排放，范围3=价值链其他间接排放（通常占比最大、最难核算）。规范书写 lingkup 3（分写）。",
        "synonyms": ["lingkup tiga（全拼写法）", "Scope 3（英语原称）"],
        "antonyms": [],
        "examples": [
            ("脱碳减排", "Emisi rantai pasok termasuk kategori lingkup 3 dalam laporan karbon.", "供应链排放归入碳报告的范围3类别。"),
            ("商务", "Penghitungan lingkup 3 membutuhkan data dari ratusan pemasok.", "范围3核算需要数百家供应商的数据。"),
        ],
    },
    {
        "word": "menetapkan",
        "cn": "规定；设定",
        "en": "to stipulate; to set",
        "root": "tetap（固定——本土词）+ me- + -kan → menetapkan",
        "forms_note": "menetapkan 动词；ditetapkan 被动动词；penetapan 名词（规定；决定）；tetap 形容词（固定的）；ketetapan 名词（法令）",
        "note": "",
        "synonyms": ["mengatur（规定）", "menentukan（确定）", "memutuskan（决定）"],
        "antonyms": ["menyimpang（偏离——指既定标准）"],
        "examples": [
            ("项目管理", "Direksi menetapkan sasaran pengurangan emisi tiga puluh persen dalam lima tahun.", "董事会设定五年内减排30%的目标。"),
            ("商务", "Pemerintah menetapkan kuota ekspor nikel setiap semester.", "政府每学期规定镍出口配额。"),
        ],
    },
    {
        "word": "sasaran",
        "cn": "目标",
        "en": "target; goal",
        "root": "sasaran（目标——本土词，语源不确定[待核实]）",
        "forms_note": "sasaran 名词；menyasar 动词（瞄准）；disasarkan 被动动词（被瞄准）",
        "note": "",
        "synonyms": ["target（目标——英语借词）", "tujuan（目的）"],
        "antonyms": [],
        "examples": [
            ("项目管理", "Sasaran produksi tahunan tercapai seratus empat persen berkat perbaikan proses.", "因流程改进，年度生产目标达成104%。"),
            ("脱碳减排", "Sasaran netralitas karbon 2060 tertuang dalam dokumen kebijakan nasional.", "2060碳中和目标已写入国家政策文件。"),
        ],
    },
    {
        "word": "pengurangan",
        "cn": "减少；削减",
        "en": "reduction",
        "root": "kurang（少——本土词）+ pe- + -an → pengurangan（名词化）",
        "forms_note": "mengurangi 动词；dikurangi 被动动词；pengurangan 名词；pengurang 名词（减少剂——化学义）",
        "note": "",
        "synonyms": ["penurunan（下降）", "pemangkasan（削减）"],
        "antonyms": ["peningkatan（增加）", "penambahan（添加）"],
        "examples": [
            ("脱碳减排", "Pengurangan emisi GRK menjadi kewajiban kontraktual pemasok.", "温室气体减排成为供应商的合同义务。"),
            ("项目管理", "Pengurangan limbah produksi menghemat biaya pengelolaan lingkungan.", "生产废弃物减少节约环境管理成本。"),
        ],
    },
    {
        "word": "opsi",
        "cn": "选项",
        "en": "option",
        "root": "opsi（欧洲语言借词：英 option / 荷 optie，终源拉丁语 optio「选择」）",
        "forms_note": "opsi 名词；opsional 形容词（可选的）",
        "note": "借词与本土词分工：日常口语用 pilihan；opsi 偏商务/技术文体。",
        "synonyms": ["pilihan（选择——本土词）", "alternatif（替代方案）"],
        "antonyms": ["keharusan（必须项）"],
        "examples": [
            ("商务", "Kontraktor menawarkan tiga opsi pembayaran kepada pemilik proyek.", "承包商向项目业主提供三种付款选项。"),
            ("脱碳减排", "Hidrogen hijau menjadi opsi utama untuk menggantikan batubara.", "绿氢成为替代煤炭的主要选项。"),
        ],
    },
    {
        "word": "transisi",
        "cn": "转型；过渡",
        "en": "transition",
        "root": "transisi（欧洲语言借词：英 transition / 荷 transitie，终源拉丁语 transitio「跨越」）",
        "forms_note": "transisi 名词；bertransisi 动词（处于转型中）；fase transisi 名词短语（转型期）",
        "note": "",
        "synonyms": ["peralihan（过渡——本土词）", "transformasi（转型——程度更深）"],
        "antonyms": ["kemantapan（稳定态）"],
        "examples": [
            ("脱碳减排", "Transisi energi dari batubara ke sumber terbarukan memerlukan investasi besar.", "从煤炭向可再生能源的能源转型需要巨额投资。"),
            ("项目管理", "Manajemen memastikan transisi operasi berjalan tanpa gangguan produksi.", "管理层确保运营过渡不中断生产。"),
        ],
    },
    {
        "word": "dari",
        "cn": "从；自",
        "en": "from",
        "root": "dari（前置词——本土词）",
        "forms_note": "—（无派生形态）",
        "note": "前置词，与 ke（到/向——#17）构成空间/时间范围框架：dari…ke…（从……到……）。",
        "synonyms": ["sejak（自……起——时间义）"],
        "antonyms": [],
        "examples": [
            ("项目管理", "Pengiriman bahan baku dari pelabuhan memakan waktu empat hari.", "原料从港口发运需四天。"),
            ("商务", "Harga nikel naik dari 18 ribu menjadi 22 ribu dolar AS per ton.", "镍价从每吨1.8万美元涨至2.2万美元。"),
        ],
    },
    {
        "word": "batubara",
        "cn": "煤炭",
        "en": "coal",
        "root": "batubara（合成词：batu（石——本土词）+ bara（火炭——本土词））",
        "forms_note": "batubara 名词；tambang batubara 名词短语（煤矿）；pembangkit batubara 名词短语（燃煤电厂）",
        "note": "印尼能源结构主力（发电占比超六成），也是 GRK 最大排放源；园区自备燃煤电厂是脱碳压力的焦点。勿与 karbon（碳——元素义）混淆。",
        "synonyms": [],
        "antonyms": ["energi terbarukan（可再生能源——语境反义）"],
        "examples": [
            ("脱碳减排", "Pembangkit batubara direncanakan dialihkan ke biomassa secara bertahap.", "燃煤电厂计划逐步改烧生物质。"),
            ("商务", "Harga batubara dunia memengaruhi biaya produksi listrik smelter.", "国际煤价影响冶炼厂电力成本。"),
        ],
    },
    {
        "word": "ke",
        "cn": "到；向",
        "en": "to (toward)",
        "root": "ke（前置词——本土词）",
        "forms_note": "—（无派生形态）",
        "note": "前置词，表方向/目的；与 dari（从——#15）构成 dari…ke… 框架。",
        "synonyms": ["menuju（朝着——动词性更强）"],
        "antonyms": [],
        "examples": [
            ("项目管理", "Komponen dikirim ke lokasi proyek sebelum tanggal target.", "部件在目标日期前运抵项目现场。"),
            ("商务", "Delegasi berangkat ke Jakarta untuk rapat koordinasi investor.", "代表团前往雅加达参加投资者协调会。"),
        ],
    },
    {
        "word": "biomassa",
        "cn": "生物质",
        "en": "biomass",
        "root": "biomassa（欧洲语言借词：英 biomass / 荷 biomassa；构词 bio-（生命——希腊借词）+ massa（物质——拉丁借词））",
        "forms_note": "biomassa 名词；pembangkit biomassa 名词短语（生物质电厂）；co-firing biomassa 名词短语（掺烧生物质）",
        "note": "与 batubara 共燃（co-firing）是印尼燃煤电厂短期脱碳路径；原料多为 sawit（棕榈）加工废弃物，须防与粮食争地。",
        "synonyms": ["bioenergi（生物能源——相关词）"],
        "antonyms": [],
        "examples": [
            ("脱碳减排", "Co-firing biomassa di pembangkit batubara menurunkan emisi GRK hingga dua puluh persen.", "燃煤电厂掺烧生物质可降低温室气体排放达20%。"),
            ("项目管理", "Kajian kelayakan biomassa memastikan ketersediaan limbah sawit yang cukup.", "生物质可行性研究确保棕榈废弃物供应充足。"),
        ],
    },
    {
        "word": "penangkapan",
        "cn": "捕获",
        "en": "capture",
        "root": "tangkap（捉——本土词）+ pe- + -an → penangkapan（名词化）",
        "forms_note": "menangkap 动词；ditangkap 被动动词；penangkap 名词（捕捉器；捕捉者）；penangkapan 名词",
        "note": "技术固定搭配：penangkapan karbon（碳捕获——CCS 前半段）；勿与日常义 penangkapan ikan（捕鱼）混。",
        "synonyms": ["penjaringan（截获）", "pengambilan（抓取）"],
        "antonyms": ["pelepasan（释放）"],
        "examples": [
            ("脱碳减排", "Penangkapan karbon dari cerobong asap masih dalam uji coba skala industri.", "烟气碳捕获尚处工业试验阶段。"),
            ("项目管理", "Teknologi penangkapan CO₂ terpasang di fasilitas pilot pabrik.", "CO₂捕获技术安装在工厂中试装置。"),
        ],
    },
    {
        "word": "penyimpanan",
        "cn": "储存",
        "en": "storage",
        "root": "simpan（存放——本土词）+ pe- + -an → penyimpanan（名词化）",
        "forms_note": "menyimpan 动词；disimpan 被动动词；penyimpanan 名词；tempat penyimpanan 名词短语（储存场所）",
        "note": "技术固定搭配：penyimpanan karbon（碳封存——CCS 后半段）；电池储能：penyimpanan energi baterai。",
        "synonyms": ["pergudangan（仓储）", "penimbunan（囤积——含贬义）"],
        "antonyms": ["pengeluaran（取出）"],
        "examples": [
            ("脱碳减排", "Penangkapan dan penyimpanan karbon menjadi opsi strategis industri semen.", "碳捕获与封存成为水泥产业的战略选项。"),
            ("项目管理", "Gudang penyimpanan bahan kimia memenuhi standar keselamatan internasional.", "化学品储存仓库符合国际安全标准。"),
        ],
    },
    {
        "word": "efisiensi",
        "cn": "效率",
        "en": "efficiency",
        "root": "efisiensi（欧洲语言借词：英 efficiency / 荷 efficiëntie，终源拉丁语 efficientia）",
        "forms_note": "efisiensi 名词；efisien 形容词（高效的）；inefisiensi 反义名词（低效率）",
        "note": "",
        "synonyms": ["keefisienan（效率——本土构词变体）"],
        "antonyms": ["inefisiensi（低效率）", "pemborosan（浪费）"],
        "examples": [
            ("项目管理", "Efisiensi energi meningkat dua belas persen setelah pembaruan motor listrik.", "电机更新后能效提升12%。"),
            ("商务", "Efisiensi biaya logistik menjadi fokus utama tahun ini.", "物流成本效率成为今年首要焦点。"),
        ],
    },
    {
        "word": "energi",
        "cn": "能源；能量",
        "en": "energy",
        "root": "energi（欧洲语言借词：英 energy / 荷 energie，终源希腊语 energeia「活动力」）",
        "forms_note": "energi 名词；energi terbarukan 名词短语（可再生能源）；penghematan energi 名词短语（节能）；berenergi 形容词（有能量的）",
        "note": "政策高频搭配：transisi energi（能源转型）、efisiensi energi（能效）、energi hijau（绿色能源）；官方缩写 EBT = Energi Baru Terbarukan（新能源与可再生能源）。",
        "synonyms": ["tenaga（力；能——本土词，搭配有别）"],
        "antonyms": [],
        "examples": [
            ("脱碳减排", "Pabrik beralih ke energi surya untuk memangkas biaya bahan bakar.", "工厂转用太阳能以削减燃料成本。"),
            ("项目管理", "Audit energi tahunan mengidentifikasi potensi penghematan yang besar.", "年度能源审计识别出可观的节约潜力。"),
        ],
    },
    {
        "word": "melalui",
        "cn": "通过；经由",
        "en": "through; via",
        "root": "lalu（经过——本土词）+ me- + -i → melalui",
        "forms_note": "melalui 介词/动词；lalu 词根（经过）；laluan 名词（通道）",
        "note": "介词化动词：表经由路径/手段/流程，正式文体高频——melalui proses tender（通过招标流程）。",
        "synonyms": ["lewat（经过——口语）", "melintasi（穿越）"],
        "antonyms": [],
        "examples": [
            ("项目管理", "Pengadaan dilakukan melalui proses tender terbuka yang transparan.", "采购通过透明的公开招标流程进行。"),
            ("商务", "Kemitraan strategis dicapai melalui negosiasi yang panjang.", "战略伙伴关系的达成经历了漫长谈判。"),
        ],
    },
    {
        "word": "pemulihan",
        "cn": "恢复；回收",
        "en": "recovery; restoration",
        "root": "pulih（复原——本土词）+ pe- + -an → pemulihan（名词化）",
        "forms_note": "memulihkan 动词；dipulihkan 被动动词；pulih 词根（复原）；pemulihan 名词",
        "note": "双场景：生态修复 pemulihan ekosistem（矿区复垦）/ pemulihan lahan（土地恢复）；工业热回收 pemulihan panas（余热回收）。",
        "synonyms": ["restorasi（修复——借词）", "rehabilitasi（康复；修复）"],
        "antonyms": ["degradasi（退化）", "kerusakan（破坏）"],
        "examples": [
            ("项目管理", "Pemulihan lahan pasca-tambang menjadi kewajiban pemegang izin.", "采矿后土地恢复是许可证持有者的义务。"),
            ("脱碳减排", "Pemulihan panas gas buang meningkatkan efisiensi total pembangkit.", "废气余热回收提升电厂综合效率。"),
        ],
    },
    {
        "word": "implementasi",
        "cn": "实施",
        "en": "implementation",
        "root": "implementasi（欧洲语言借词：英 implementation / 荷 implementatie，终源拉丁语 implementum）",
        "forms_note": "implementasi 名词；mengimplementasikan 动词；terimplementasi 被动（已实施）；implementor 名词（实施者）",
        "note": "",
        "synonyms": ["pelaksanaan（执行——本土词）", "penerapan（应用）"],
        "antonyms": ["penundaan（搁置）"],
        "examples": [
            ("项目管理", "Implementasi sistem ERP baru memasuki fase uji coba paralel.", "新 ERP 系统的实施进入并行测试阶段。"),
            ("脱碳减排", "Implementasi harga karbon diperluas ke sektor industri yang intensif energi.", "碳定价的实施扩大至高耗能工业部门。"),
        ],
    },
    {
        "word": "inisiatif",
        "cn": "倡议；主动性",
        "en": "initiative",
        "root": "inisiatif（欧洲语言借词：英 initiative / 荷 initiatief，终源拉丁语 initium「开端」）",
        "forms_note": "inisiatif 名词；berinisiatif 动词短语（主动提出）；penginisiasi 名词（发起人）",
        "note": "印尼语定义：kemampuan untuk memulai sesuatu terlebih dahulu（提前开始做某事的能力）——#27–#32 六个词条为其完整释义拆解。",
        "synonyms": ["prakarsa（倡议——本土构词）", "gagasan（构想）"],
        "antonyms": ["kepasifan（被动消极）"],
        "examples": [
            ("商务", "Inisiatif kolaborasi dengan universitas menghasilkan teknologi pengolahan baru.", "与高校的合作倡议催生了新的处理技术。"),
            ("项目管理", "Karyawan dihargai karena berinisiatif memperbaiki prosedur keselamatan.", "员工因主动改进安全程序而受到表彰。"),
        ],
    },
    {
        "word": "kemampuan",
        "cn": "能力",
        "en": "ability; capability",
        "root": "mampu（有能力——本土词）+ ke- + -an → kemampuan（名词化）",
        "forms_note": "mampu 形容词；kemampuan 名词；kemampuan beradaptasi 名词短语（适应能力）",
        "note": "inisiatif 定义首词（#26）：kemampuan untuk memulai sesuatu terlebih dahulu。",
        "synonyms": ["kapabilitas（能力——借词）", "kecakapan（技能）"],
        "antonyms": ["ketidakmampuan（无能）"],
        "examples": [
            ("项目管理", "Kemampuan teknis tim lokal meningkat melalui program pelatihan bersertifikat.", "通过认证培训计划，本地团队的技术能力提升。"),
            ("商务", "Uji kemampuan bayar wajib dilakukan sebelum pemberian kredit.", "放贷前必须进行偿付能力测试。"),
        ],
    },
    {
        "word": "untuk",
        "cn": "为了；用于",
        "en": "for; in order to",
        "root": "untuk（前置词——本土词）",
        "forms_note": "—（无派生形态）",
        "note": "目的前置词：后接动词原形构成目的状语——menghemat energi untuk mengurangi emisi（节能以减少排放）；正式变体 guna、bagi 近义。",
        "synonyms": ["guna（为了——正式文体）", "bagi（对于）"],
        "antonyms": [],
        "examples": [
            ("项目管理", "Jadwal padat disusun untuk memastikan pengerjaan tepat waktu.", "编制紧凑进度表以确保按期完工。"),
            ("脱碳减排", "Panel surya dipasang untuk memangkas ketergantungan pada listrik batubara.", "安装光伏板以削减对煤电的依赖。"),
        ],
    },
    {
        "word": "memulai",
        "cn": "开始",
        "en": "to begin; to start",
        "root": "mulai（开始——本土词）+ me- → memulai",
        "forms_note": "memulai 动词；dimulai 被动动词；permulaan 名词（开端）",
        "note": "inisiatif 定义动词（#26）：memulai sesuatu terlebih dahulu（提前开始做某事）。",
        "synonyms": ["mengawali（开始）", "membuka（开启）"],
        "antonyms": ["mengakhiri（结束）", "menyelesaikan（完成）"],
        "examples": [
            ("项目管理", "Kontraktor memulai pekerjaan fondasi pada kuartal pertama.", "承包商于第一季度开工基础工程。"),
            ("商务", "Perusahaan memulai operasi komersial setelah uji coba enam bulan.", "公司经过六个月试运行后启动商业化运营。"),
        ],
    },
    {
        "word": "sesuatu",
        "cn": "某事；某物",
        "en": "something",
        "root": "sesuatu（合成不定代词：se-（一）+ suatu（某个））",
        "forms_note": "sesuatu 不定代词；suatu 词（某个——指不确定事物）",
        "note": "不定代词，指未指明的事物；常搭配 sesuatu yang baru（新的东西——#26 inisiatif 定义组成词）。",
        "synonyms": [],
        "antonyms": ["tidak ada apa-apa（什么也没有）"],
        "examples": [
            ("项目管理", "Harus ada sesuatu yang berubah dalam prosedur setelah insiden itu.", "事故发生后，规程中必须有某些改变。"),
            ("商务", "Klien meminta sesuatu yang belum pernah diproduksi sebelumnya.", "客户提出了前所未有的需求。"),
        ],
    },
    {
        "word": "terlebih",
        "cn": "更加；提前",
        "en": "more; beforehand",
        "root": "lebih（更——本土词）+ ter- → terlebih",
        "forms_note": "terlebih 副词；terlebih dahulu 固定短语（首先；提前）",
        "note": "双义：①比较级强化 terlebih penting（更为重要）；②固定短语 terlebih dahulu（首先、提前——#26/#32 联记）。",
        "synonyms": ["lebih-lebih（更加）", "terutama（尤其）"],
        "antonyms": [],
        "examples": [
            ("项目管理", "Persetujuan izin lingkungan harus diperoleh terlebih dahulu.", "环评许可必须事先取得。"),
            ("商务", "Syarat mutu menjadi terlebih penting dalam kontrak jangka panjang.", "质量条款在长期合同中更加重要。"),
        ],
    },
    {
        "word": "dahulu",
        "cn": "以前；首先",
        "en": "previously; first",
        "root": "dahulu（本土词，为 dulu（从前）的扩展形式）",
        "forms_note": "dahulu 副词；dulu 口语变体；lebih dahulu 短语（更早地）",
        "note": "inisiatif 定义末词（#26）：terlebih dahulu（提前）。",
        "synonyms": ["dulu（以前——口语）", "sebelumnya（先前）"],
        "antonyms": ["kemudian（随后）", "kelak（将来）"],
        "examples": [
            ("项目管理", "Evaluasi risiko dilakukan dahulu sebelum pekerjaan dimulai.", "开工前先进行风险评估。"),
            ("商务", "Model bisnis ini terbukti berhasil dahulu di pasar regional.", "该商业模式此前已在区域市场验证成功。"),
        ],
    },
    {
        "word": "peluang",
        "cn": "机会",
        "en": "opportunity; chance",
        "root": "peluang（本土词，语源不确定[待核实]）",
        "forms_note": "peluang 名词；berpeluang 动词（有机会）；memanfaatkan peluang 动词短语（把握机会）",
        "note": "SWOT 分析对位：peluang（机会）vs ancaman（威胁）；商务高频 peluang bisnis（商机）。",
        "synonyms": ["kesempatan（机会）", "oportunitas（机会——借词）"],
        "antonyms": ["ancaman（威胁）"],
        "examples": [
            ("商务", "Transisi hijau membuka peluang bisnis baru di sektor energi bersih.", "绿色转型在清洁能源领域开辟新商机。"),
            ("项目管理", "Keterlambatan ini justru memberikan peluang untuk revisi metodologi.", "此次延误反而提供了修订方法论的机会。"),
        ],
    },
]
