# -*- coding: utf-8 -*-
# BIT V1.0 词条批次 1005-b2（10词）——供应链管理/商务谈判/冶炼园区语境
# 格式：word/cn/en/root/forms_note/note/synonyms/antonyms/examples

ENTRIES = [
    {
        "word": "konsumen",
        "cn": "消费者；客户",
        "en": "consumer; customer",
        "root": "借词：荷兰语 konsument ← 拉丁语 consumere（消费）；经殖民时期进入印尼语",
        "forms_note": "konsumsi 名词（消费）；mengonsumsi 动词（消费）；konsumtif 形容词（消费性的）；konsumerisme 名词（消费主义）",
        "note": "供应链末端角色词：produsen（生产者）→ distributor（分销商）→ konsumen（消费者）。",
        "synonyms": ["pelanggan（顾客）", "pembeli（购买者）"],
        "antonyms": ["produsen（生产者）", "pemasok（供应商）"],
        "examples": [
            ("供应链管理", "Konsumen akhir global semakin menuntut sertifikasi rendah karbon untuk nikel.", "全球终端消费者日益要求镍产品具备低碳认证。"),
            ("商务谈判", "Harga jual kepada konsumen kontrak jangka panjang ditinjau setiap semester.", "对长期合同客户的销售价格每学期复审一次。"),
        ],
    },
    {
        "word": "tepat",
        "cn": "准确的；准时的",
        "en": "accurate; exact; on time",
        "root": "本土词（词根 tepat，不可拆分）",
        "forms_note": "ketepatan 名词（准确性；准时性）；menepati 动词（遵守；履行）；tepatnya 副词（确切说）",
        "note": "tepat waktu = 准时；tepat sasaran = 命中目标；两义在商务文本中均高频。",
        "synonyms": ["akurat（准确）", "presisi（精密）", "cermat（缜密）"],
        "antonyms": ["meleset（偏差；未中）", "keliru（错误）"],
        "examples": [
            ("项目管理", "Jadwal kirim harus tepat agar pemuatan kapal tidak tertunda.", "发运进度必须准时，以免船舶装载延误。"),
            ("商务谈判", "Angka volume dalam kontrak harus tepat dan dapat diverifikasi kedua pihak.", "合同中的数量数字须准确且双方可核验。"),
        ],
    },
    {
        "word": "pas",
        "cn": "合适的；刚好的；吻合的",
        "en": "fit; just right; exactly matching",
        "root": "本土词（词根 pas，不可拆分）",
        "forms_note": "memasang 动词（安装；张贴）；terpasang 被动完成（已装上）；pasangan 名词（一对；伴侣）；pemasangan 名词（安装）；sepadan 形容词（相称）",
        "note": "口语与正式文本均高频；尺码、容量、时间安排'刚好匹配'均用 pas。",
        "synonyms": ["cocok（合适）", "sesuai（相符）", "sepadan（相称）"],
        "antonyms": ["kebesaran（过大）", "kekecilan（过小）"],
        "examples": [
            ("供应链管理", "Kapasitas tangki penampung harus pas dengan volume kebutuhan harian.", "储罐容量须与每日需求量刚好匹配。"),
            ("工程建设", "Posisi fondasi harus pas dengan sumbu kolom struktur baja.", "基础位置须与钢柱轴线精确对正。"),
        ],
    },
    {
        "word": "kaget",
        "cn": "吃惊；惊讶",
        "en": "startled; surprised; shocked",
        "root": "本土词（词根 kaget，不可拆分）",
        "forms_note": "mengagetkan 动词（使吃惊）；dikagetkan 被动（被吓到）；无标准名词派生",
        "note": "口语高频；书面语常用同义词 terkejut 替代，但 kaget 在汇报对话中更自然。",
        "synonyms": ["terkejut（受惊）", "terperanjat（愕然）"],
        "antonyms": ["tenang（镇定）"],
        "examples": [
            ("项目管理", "Kami kaget dengan kenaikan mendadak tarif pelabuhan minggu ini.", "我们对本周港口费突然上调感到吃惊。"),
            ("商务谈判", "Jangan kaget jika penawaran pertama jauh di atas perkiraan.", "若首轮报价远高于预期，不必吃惊。"),
        ],
    },
    {
        "word": "kasar",
        "cn": "粗糙的；粗鲁的",
        "en": "coarse; rough; rude",
        "root": "本土词（疑源自古爪哇语，今作纯词根处理，不可拆分）",
        "forms_note": "kekasaran 名词（粗糙；粗鲁）；mengasari 动词（粗暴对待某人）",
        "note": "双义并行：质地义（kasar 的表面）与行为义（kasar 的态度）；商务场合行为义属失礼信号。",
        "synonyms": ["tidak halus（不光滑）", "kurang ajar（无礼）"],
        "antonyms": ["halus（光滑；文雅）", "lembut（柔和）", "sopan（礼貌）"],
        "examples": [
            ("工程建设", "Lapisan permukaan jalan masih kasar sebelum pengaspalan final.", "道路面层在最终摊铺沥青前仍显粗糙。"),
            ("商务谈判", "Sikap kasar dalam rapat merusak suasana negosiasi yang konstruktif.", "会议中的粗鲁态度破坏了建设性谈判氛围。"),
        ],
    },
    {
        "word": "perkirakan",
        "cn": "估算；估计",
        "en": "estimate; reckon (imperative/root form)",
        "root": "kira（估计——本土词）+ per-...-kan 派生（强化/使动）→ perkirakan（估算）",
        "forms_note": "memperkirakan 标准主动式；diperkirakan 被动式（据估计——最高频）；perkiraan 名词（估计；预报）",
        "note": "词条为省略 meng- 的祈使/不定形式，标准主动式为 memperkirakan；实际文本中最常见被动式 diperkirakan（据估计）。",
        "synonyms": ["menaksir（估价）", "estimasi（估计——名词借词）", "menganggarkan（预算）"],
        "antonyms": ["memastikan（确定）", "menghitung pasti（精算）"],
        "examples": [
            ("项目管理", "Perkirakan durasi pekerjaan sebelum menandatangani jadwal induk.", "在签署主进度表前先估算工期。"),
            ("供应链管理", "Analis memperkirakan harga kokas impor stabil hingga akhir kuartal.", "分析师预计进口焦炭价格至本季末保持稳定。"),
        ],
    },
    {
        "word": "jumlah",
        "cn": "总数；数量；金额",
        "en": "total; quantity; amount",
        "root": "阿拉伯语借词 jumlah（جملة，整体；总和），经贸易时期进入印尼语",
        "forms_note": "berjumlah（总计为）；menjumlahkan（合计）；penjumlahan（加法；汇总）；sejumlah（一定数量的）",
        "note": "jumlah uang = 金额；jumlah total 连用为同义反复，正式文本择一即可。",
        "synonyms": ["total（总量——借词）", "keseluruhan（全部）", "kuantitas（数量）"],
        "antonyms": ["sebagian（部分）", "sedikit（少量）"],
        "examples": [
            ("供应链管理", "Jumlah kiriman aktual dibandingkan dengan order setiap minggu.", "每周将实际发货总数与订单核对。"),
            ("商务谈判", "Jumlah denda keterlambatan dihitung berdasarkan hari kalender.", "迟延违约金金额按日历日计算。"),
        ],
    },
    {
        "word": "kemasan",
        "cn": "包装",
        "en": "packaging; package",
        "root": "kemas（整理妥当；装束整齐——本土词）+ -an（名词后缀）→ kemasan（包装）",
        "forms_note": "mengemas 动词（包装）；pengemasan 名词（包装过程；包装行业）；pengemas 名词（包装者；包装机）；terkemas 被动完成（已包装）",
        "note": "",
        "synonyms": ["pembungkusan（包裹）", "bungkusan（包件）"],
        "antonyms": [],
        "examples": [
            ("供应链管理", "Kemasan karung ganda dipakai untuk pengiriman bahan kimia ke smelter.", "发往冶炼厂的化学品采用双层袋包装。"),
            ("商务谈判", "Perubahan desain kemasan memerlukan persetujuan tertulis dari pembeli.", "包装设计变更须取得买方书面同意。"),
        ],
    },
    {
        "word": "ikat",
        "cn": "捆；绑",
        "en": "to tie; to bind",
        "root": "本土词（词根 ikat，捆绑）",
        "forms_note": "mengikat 动词（捆绑）；ikatan 名词（捆；关系；束缚）；pengikat 名词（捆扎物；系带）；terikat 被动（被捆；受约束）",
        "note": "高频搭配 ikat pinggang（腰带），字面义'捆腰'；工业 PPE 中 sabuk pengaman（全身式安全带）勿与其混用。",
        "synonyms": ["mengikat（捆绑——动词）", "menambat（系泊）"],
        "antonyms": ["melepaskan（松开）", "membuka（解开）"],
        "examples": [
            ("供应链管理", "Kawat baja dipakai untuk mengikat gulungan kabel saat pengiriman.", "运输时用钢丝捆扎电缆卷盘。"),
            ("日常用语", "Ikat pinggang kerja wajib dikenakan di area produksi sesuai SOP keselamatan.", "按安全 SOP，生产区域须佩戴工作腰带。"),
        ],
    },
    {
        "word": "pinggang",
        "cn": "腰部；腰",
        "en": "waist; lower back",
        "root": "本土词（词根 pinggang，不可拆分）",
        "forms_note": "—（无派生形态）；常见合成词 ikat pinggang（腰带）",
        "note": "核心搭配 ikat pinggang（腰带）；工地语境 nyeri pinggang（腰痛）为高频健康议题。",
        "synonyms": [],
        "antonyms": [],
        "examples": [
            ("日常用语", "Seragam lapangan dilengkapi ikat pinggang dengan logo perusahaan.", "现场工装配有公司标志腰带。"),
            ("工程建设", "Nyeri pinggang adalah keluhan umum pekerja bongkar muat manual.", "腰痛是人力装卸工人的常见不适。"),
        ],
    },
]
